Remove timbre dependency
Always log failures to stdout, removing timbre (and some other transitive deps) as a dependency.

Printing to stdout is the default behavior for timbre, so for users that do not configure it explicitly no change is expected (other than a small format difference).

Exceptions are still printed using pretty, so the output for stack traces is exactly the same.

Output before:
```
2025-01-15T19:57:07.903Z marco.local INFO [state-flow.core:241] - Flow "root (core_test.clj:26) -> child2 (core_test.clj:28) -> bogus" failed with exception
             clojure.core/with-bindings*       core.clj: 1990 (repeats 2 times)
                                     ...
                       clojure.core/eval       core.clj: 3232
                          user/eval16619     REPL Input:
                  clojure.test/run-tests       test.clj:  768 (repeats 2 times)
                                     ...
java.lang.Exception: My exception
```

Output after:
```
Flow "root (core_test.clj:26) -> child2 (core_test.clj:28) -> bogus" failed with exception
             clojure.core/with-bindings*       core.clj: 1990 (repeats 2 times)
                                     ...
                       clojure.core/eval       core.clj: 3232
                          user/eval16619     REPL Input:
                  clojure.test/run-tests       test.clj:  768 (repeats 2 times)
                                     ...
java.lang.Exception: My exception
```

Classpath difference:
```
|                     :dep | :upstream | :head |
|--------------------------+-----------+-------|
|      com.taoensso/encore |   3.128.0 |       |
|      com.taoensso/timbre |     6.6.1 |       |
|       com.taoensso/truss |    1.12.0 |       |
| org.clojure/tools.reader |     1.5.0 |       |
|   org.clj-commons/pretty |     3.2.0 | 3.3.0 |
```